# Generated by Django 3.2.12 on 2022-05-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=250)),
                ('movie_link', models.CharField(max_length=250)),
                ('movie_year', models.CharField(max_length=100)),
                ('movie_nomination', models.CharField(max_length=13)),
            ],
        ),
    ]
