# Generated by Django 3.2.12 on 2022-05-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_nomination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_year',
            field=models.CharField(max_length=255),
        ),
    ]
